### PR TITLE
port to firefox

### PR DESCRIPTION
**Pull request by chelovechishko**
Did not check with chrome.
Now just a random id string, or you will just use email of yours?

### CODE REVIEW

**Comment by yaronf** [comment]
> Did not check with chrome.
> Now just a random id string, or you will just use email of yours?

I'm OK with the random string, thanks!

**Comment by yaronf** [comment]
Hmmm. Merged, ran "make", Firefox refuses to load the add-on. Firefox 81 on MacOS. Says:

```
File /Users/ysheffer/misc/overlay-clock/overlay-clock-0.7.zip does not contain a valid manifest
```

**Comment by chelovechishko** [comment]
It was the least i could do.

**Comment by chelovechishko** [comment]
unzip -l output should look like just files not directory/files.
Like: `zip -r --junk-paths overlay-clock.xpi ./overlay-clock`

**Comment by yaronf** [comment]
OK, I added this to the makefile, and tried it on Firefox Dev Edition. It installs but I'm not seeing the icon.

**Comment by chelovechishko** [comment]
Oh, shi~, forget, that for not signed add-ons
`xpinstall.signatures.required` should be false in `about:config` (and
some restrictions about which versions of firefox could has it at
all...). Could it be, that the problem only with this?

Also, if cautionary warning of unknown property bothers, then
`sed -i 's;"update_url";// &;' overlay-clock/manifest.json && zip ...
&& sed -i 's;// "update_url";&;' overlay-clock/manifest.json`
will be good enough, i guess.

**Comment by yaronf** [comment]
I had to install FF Dev Edition (latest beta edition) *and* toggle this flag to install. So now it’s not complaining about the manifest anymore and it’s happily installing the add-on, but there’s no toolbar icon.

**Comment by yaronf** [comment]
Sorry, I can see the icon (it's just very hard to see on the dark toolbar of the Dev Edition.

**Pull request merged**
