### PR TITLE
refactoring, update to 0.4

### PR DESCRIPTION
**Pull request by chelovechishko**

### CODE REVIEW

**Comment by yaronf** [comment]
Could you re-enable the "only for full screen" functionality? For me (and many others) there's a system clock visible when the browser is not in full-screen mode, and this extra clock is distracting.

Also, there seems to be a problem with the Z level of the clock. When I tried on [this site](http://www.haaretz.co.il/), the clock disappears behind the stripe at the top of the screen.

**Comment by yaronf** [comment]
Sorry, after merging it back to my repo, I noticed that color selection doesn't work correctly (both at the level of the options dialog and also the actual clock). Will need to recheck before uploading to the Store.

**Comment by yaronf** [comment]
On second look everything is fine, and I published it. It will take some time before it is available on the Chrome Web Store.

**Comment by chelovechishko** [comment]
Thank you.

**Pull request merged**
